// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  loadingSpinner: string;
  loginButton: string;
  loginContainer: string;
  loginErrorMessage: string;
}
export const cssExports: CssExports;
export default cssExports;
