// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cancelButton: string;
  closeButton: string;
  passwordError: string;
  registerBody: string;
  registerContainer: string;
  registerContent: string;
  registerFooter: string;
  registerHeader: string;
  registerTitle: string;
}
export const cssExports: CssExports;
export default cssExports;
